"""
Script generator — converts a phenomenon description into a production spec.

In the current workflow, the script is generated by Claude (me) in the conversation
and passed to this module as structured data. This module validates, formats, and
prepares the spec for the pipeline.

A spec is a dict with:
    title       : str   — hook title displayed on screen
    script      : str   — narration text sent to TTS (full voiceover)
    scene_file  : str   — absolute path to the Manim scene Python file
    scene_class : str   — Manim class name inside that file
    slug        : str   — short identifier for output filenames (no spaces)
"""

import re
import os
from pathlib import Path

ROOT = Path(__file__).parent.parent


def build_spec(
    title: str,
    script: str,
    scene_file: str,
    scene_class: str,
    slug: str
) -> dict:
    """
    Validate and return a production spec dict.
    Raises ValueError if any required field is missing or the scene file doesn't exist.
    """
    if not title.strip():
        raise ValueError("title is empty")
    if not script.strip():
        raise ValueError("script is empty")

    scene_path = Path(scene_file)
    if not scene_path.is_absolute():
        scene_path = ROOT / scene_file
    if not scene_path.exists():
        raise ValueError(f"scene_file not found: {scene_path}")

    slug = _slugify(slug)

    return {
        "title": title.strip(),
        "script": script.strip(),
        "scene_file": str(scene_path),
        "scene_class": scene_class.strip(),
        "slug": slug,
    }


def _slugify(text: str) -> str:
    text = text.lower().strip()
    text = re.sub(r"[^\w\s-]", "", text)
    text = re.sub(r"[\s_]+", "_", text)
    return text[:48]


# ── Pre-built spec for Wild Horse Effect (ref_001 reproduction) ───────────────

WILD_HORSE_EFFECT_SPEC = build_spec(
    title="Not Everything Is Against You..",
    script="""There's a story about a snake that slithered across a saw.

It got slightly cut.

Instead of moving away, it wrapped itself around the saw to fight back.
The tighter it squeezed, the more it bled.

It died trying to defeat something that wasn't attacking it.

Psychology calls this the Wild Horse Effect.

Sometimes the problem isn't the situation.
It's our reaction to it.

Not every criticism is an attack.
Not every silence is rejection.
Not every delay is disrespect.

The more we fight imagined threats,
the more damage we create ourselves.

Calm is power.""",
    scene_file="scenes/wild_horse_effect.py",
    scene_class="WildHorseEffect",
    slug="wild_horse_effect"
)
